colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = false

enableSearch = false
enableCodeCopy = true

[header]
  layout = "basic"

[footer]
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = false
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 5
  showMoreLink = false

[article]
  showDate = false
  showAuthor = false
  showReadingTime = false
  showTableOfContents = true
  showBreadcrumbs = true
  showHeadingAnchors = true
  showPagination = true
  showWordCount = false

[list]
  showBreadcrumbs = true
  showSummary = true
  groupByYear = false
